#! /bin/sh

# run all test cases or stop at first failure?
if [ "x$1" = "x-a" ]; then
    RUNALL=1
fi

# set unless overriden
: ${Y2BASE:=/usr/lib/YaST2/bin/y2base}
# load modules from the proper directory
export Y2DIR=.
MODDIR=tests
rm -f $Y2DIR/modules
ln -s $MODDIR $Y2DIR/modules
trap "rm -f $Y2DIR/modules" EXIT TERM

RET=0
for SCRIPT in tests/*.ycp; do
    BASE=${SCRIPT%.ycp}
    OUT=$BASE.out
    ERR=$BASE.err
    BASE=${BASE#tests/}

    echo ----- $BASE
    CASEOK=true
    # y2log to stderr, take specified namespace from Perl
    $Y2BASE -l - -n $BASE=perl $SCRIPT testsuite > tmp.out.$BASE 2> tmp.err.$BASE
    # filter out variable information
    sed --in-place -e 's/^....-..-.. ..:..:.. \(<.> \)[^ ]* /\1/' tmp.err.$BASE
    diff -u $ERR tmp.err.$BASE || CASEOK=false
    diff -u $OUT tmp.out.$BASE || CASEOK=false

    if ! $CASEOK; then
	RET=1
	[ -n $RUNALL ] || break
    fi
done

exit $RET
