# author: Martin Lazar <mlazar@suse.cz>

include $(BASEDIR)/Makefile.swig

BLOCXX_INCLUDES	= -I/usr/include
BLOCXX_LDFLAGS	= -L/usr/lib -Xlinker -rpath -Xlinker /usr/lib
BLOCXX_LIBS	= -lblocxx

SWIGFLAGS	+= $(BLOCXX_INCLUDES)
CPPFLAGS	+= $(BLOCXX_INCLUDES)
LDFLAGS		+= $(BLOCXX_LDFLAGS)
LDLIBS		+= $(BLOCXX_LIBS)
